"""initial schema

Revision ID: 803153c85c70
Revises: 
Create Date: 2026-08-28 06:12:47.966778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803153c85c70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_samples_t'), 'environment_samples', ['t'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('algo', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('trained_at', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('ref_code', sa.String(length=32), nullable=False),
    sa.Column('issue', sa.String(length=256), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_ref_code'), 'recommendations', ['ref_code'], unique=False)
    op.create_table('station_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('sensors_expected', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('takt_seconds', sa.Float(), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('config_path', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_plant_id'), 'production_lines', ['plant_id'], unique=False)
    op.create_table('production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.Float(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batches_code'), 'production_batches', ['code'], unique=False)
    op.create_index(op.f('ix_production_batches_line_id'), 'production_batches', ['line_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('zone', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('sensor_profile', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('has_tool', sa.Boolean(), nullable=False),
    sa.Column('is_inspection', sa.Boolean(), nullable=False),
    sa.Column('env_sensitive', sa.Boolean(), nullable=False),
    sa.Column('baseline_cycle_mu', sa.Float(), nullable=False),
    sa.Column('baseline_cycle_sigma', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['station_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=False)
    op.create_index(op.f('ix_stations_line_id'), 'stations', ['line_id'], unique=False)
    op.create_index(op.f('ix_stations_type_id'), 'stations', ['type_id'], unique=False)
    op.create_index(op.f('ix_stations_zone'), 'stations', ['zone'], unique=False)
    op.create_table('data_quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.Float(), nullable=False),
    sa.Column('sensor_coverage', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('freshness_s', sa.Float(), nullable=False),
    sa.Column('anomaly_rate', sa.Float(), nullable=False),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_metrics_station_id'), 'data_quality_metrics', ['station_id'], unique=False)
    op.create_table('machine_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('wear', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_events_station_id'), 'machine_events', ['station_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_station_id'), 'sensors', ['station_id'], unique=False)
    op.create_table('station_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('queue_len', sa.Integer(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('wear', sa.Float(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_kpis_station_id'), 'station_kpis', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_kpis_t'), 'station_kpis', ['t'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=16), nullable=False),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_batch_id'), 'vehicles', ['batch_id'], unique=False)
    op.create_index(op.f('ix_vehicles_line_id'), 'vehicles', ['line_id'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_variant'), 'vehicles', ['variant'], unique=False)
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_station_id'), 'anomalies', ['station_id'], unique=False)
    op.create_index(op.f('ix_anomalies_t'), 'anomalies', ['t'], unique=False)
    op.create_index(op.f('ix_anomalies_vehicle_id'), 'anomalies', ['vehicle_id'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('true_root_causes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_station_id'), 'defects', ['station_id'], unique=False)
    op.create_index(op.f('ix_defects_vehicle_id'), 'defects', ['vehicle_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_station_id'), 'inspections', ['station_id'], unique=False)
    op.create_index(op.f('ix_inspections_vehicle_id'), 'inspections', ['vehicle_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('as_of_seq', sa.Integer(), nullable=False),
    sa.Column('defect_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('top_features', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_vehicle_id'), 'predictions', ['vehicle_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_station_id'), 'sensor_readings', ['station_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_t'), 'sensor_readings', ['t'], unique=False)
    op.create_index(op.f('ix_sensor_readings_vehicle_id'), 'sensor_readings', ['vehicle_id'], unique=False)
    op.create_table('vehicle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.Float(), nullable=False),
    sa.Column('exited_at', sa.Float(), nullable=True),
    sa.Column('cycle_time', sa.Float(), nullable=True),
    sa.Column('cycle_dev', sa.Float(), nullable=True),
    sa.Column('queue_seen', sa.Integer(), nullable=True),
    sa.Column('checklist_result', sa.String(length=8), nullable=True),
    sa.Column('inspection_result', sa.String(length=8), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('internal_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_events_station_id'), 'vehicle_events', ['station_id'], unique=False)
    op.create_index(op.f('ix_vehicle_events_vehicle_id'), 'vehicle_events', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_events_vehicle_id'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_station_id'), table_name='vehicle_events')
    op.drop_table('vehicle_events')
    op.drop_index(op.f('ix_sensor_readings_vehicle_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_t'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_station_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_predictions_vehicle_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_inspections_vehicle_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_station_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_defects_vehicle_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_station_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_anomalies_vehicle_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_t'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_station_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_variant'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_line_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_batch_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_station_kpis_t'), table_name='station_kpis')
    op.drop_index(op.f('ix_station_kpis_station_id'), table_name='station_kpis')
    op.drop_table('station_kpis')
    op.drop_index(op.f('ix_sensors_station_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_machine_events_station_id'), table_name='machine_events')
    op.drop_table('machine_events')
    op.drop_index(op.f('ix_data_quality_metrics_station_id'), table_name='data_quality_metrics')
    op.drop_table('data_quality_metrics')
    op.drop_index(op.f('ix_stations_zone'), table_name='stations')
    op.drop_index(op.f('ix_stations_type_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_line_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_production_batches_line_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_code'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_index(op.f('ix_production_lines_plant_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_table('station_types')
    op.drop_index(op.f('ix_recommendations_ref_code'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('plants')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_environment_samples_t'), table_name='environment_samples')
    op.drop_table('environment_samples')
    # ### end Alembic commands ###
